ministryofjustice/money-to-prisoners-api

docker-compose.yml
mtp_api/settings/base.py

At present, we have to manually initialise the containers' `mtp_api` database, but the postgres image we're using for our database comes with a pre-configured `postgres` database.
[The documentation](https://registry.hub.docker.com/_/postgres/) says this database is “meant for use by users, utilities and third party applications”. Given that docker-compose is only used for development/testing, we probably don't need a dedicated new DB created, so we can just use the default postgres DB in Django.
I also tried setting a `POSTGRES_DB` environment variable and [letting the postgres container's entrypoint set up the database](https://github.com/docker-library/postgres/blob/master/9.4/docker-entrypoint.sh#L64), but the new DB doesn't appear to be ready in time for the django container to run …

Make DB name configurable for use in devenvs

---

mtp_api/apps/core/management/commands/load_test_data.py
mtp_api/apps/core/permissions.py
mtp_api/apps/mtp_auth/fixtures/initial_groups.json
mtp_api/apps/mtp_auth/tests/mommy_recipes.py
mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/transaction/migrations/0005_auto_20150727_1610.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/tests/test_views.py
mtp_api/apps/transaction/views.py

So that only users with the right permissions can access the transaction endpoints.
Done by using Django permissions + DRF Django Permission class.
I had to subclass the latter to support permission checks on GETs as not enabled by default.
We will use Django groups (Prison Clerk in this case) to manage these permissions.

Add permission checks to transaction endpoints

---

mtp_api/apps/core/permissions.py
mtp_api/apps/core/tests/test_permissions.py
mtp_api/apps/mtp_auth/fixtures/initial_groups.json
mtp_api/apps/transaction/migrations/0006_auto_20150807_1554.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/permissions.py
mtp_api/apps/transaction/views.py

This creates a new ActionsBasedPermissions to manage permissions on a view.
The old version couldn't distinguish between a POST to create a transaction
and a POST to take a transaction.
The new version checks for individual permissions so that they can be
assigned and managed better.

Refactor permission checking

---

mtp_api/apps/core/tests/utils.py
mtp_api/apps/prison/migrations/0002_prisonerlocation.py
mtp_api/apps/prison/migrations/0003_remove_prisonerlocation_upload_counter.py
mtp_api/apps/prison/models.py
mtp_api/apps/prison/serializers.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/tests/utils.py
mtp_api/apps/prison/views.py
mtp_api/apps/transaction/tests/utils.py
mtp_api/urls.py

New endpoint allowing the creation of multiple prisoner locations at the same time.
This simulates a report upload but it's a lot cleaner/easier to understand and safer.
The format is:
CREATE   /prisoner-locations/
[
{
prisoner_number: "<prisoner-number>",  # e.g. L2513UV
prisoner_dob: "<prisoner-dob>",  # e.g. 1980-06-17
prison: "<prison-id>"  # e.g. prison-1
},
{
prisoner_number: "<prisoner-number>",  # e.g. L2513UV
prisoner_dob: "<prisoner-dob>",  # e.g. 1980-06-17
prison: "<prison-id>"  # e.g. prison-1
}
]  
The system would store the items and update an `upload_counter` incremented field on each one of them which can be used later on to group them.
**Pros**
* easy to understand
* we don't need to store any files
**Cons**
* clients would have to pre-process the data
* each call to the …

PrisonerLocation model and endpoint

---

mtp_api/apps/core/tests/utils.py
mtp_api/apps/mtp_auth/fixtures/initial_groups.json
mtp_api/apps/mtp_auth/tests/mommy_recipes.py
mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/views.py
mtp_api/apps/transaction/tests/test_views.py
mtp_api/apps/transaction/tests/utils.py

This makes sure that only users beloging to the PrisonerLocationAdmin group can access the PrisonerLocation API.

Add Permission Checks to PrisonerLocationView

---

mtp_api/apps/core/tests/utils.py
mtp_api/apps/mtp_auth/constants.py
mtp_api/apps/mtp_auth/permissions.py
mtp_api/apps/mtp_auth/tests/test_permissions.py
mtp_api/apps/mtp_auth/tests/utils.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/views.py
mtp_api/apps/transaction/permissions.py
mtp_api/apps/transaction/tests/test_views.py
mtp_api/apps/transaction/views.py
requirements/dev.txt

This adds per-application permissions to the transaction and prisoner locations views so that they can't be accessed by users who logged in using a different oauth application.
- Oauth application ids are now constants so that we can reference them during our tests and when live without hardcoding them every time.
- Replaced the `force_authenticate` call with a token-based one during tests so that we can reliably test the authentication/permissions bit

Per application permissions

---

mtp_api/apps/transaction/permissions.py
mtp_api/apps/transaction/routers.py
mtp_api/apps/transaction/serializers.py
mtp_api/apps/transaction/tests/test_views.py
mtp_api/apps/transaction/urls.py
mtp_api/apps/transaction/views.py

This namespaces the cashbook transactions endpoint:
previously: /transactions/
now: /cashbook/transactions/
so that the context is clear when using them.

Namespace cashbook transactions

---

mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/api/cashbook/serializers.py
mtp_api/apps/transaction/api/cashbook/views.py
mtp_api/apps/transaction/tests/test_cashbook_views.py

The cashbook is sending ids as strings but the API is expecting integers.
I could have changed the cashbook but I've noticed that we are using ints everywhere else so I thought it would be cleaner to cast ids to integers in the API unlock view.

Cast ids to int when locking

---

mtp_api/apps/mtp_auth/serializers.py
mtp_api/apps/mtp_auth/tests/test_views.py

This fixes a problem with users (e.g. bank admins) without PrisonUserMapping model. The code is not catching the case and failing silently.

Fail safe if logged user doesn't manage any prisons

---

mtp_api/apps/transaction/api/bank_admin/serializers.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py

This is required for reconciliation - prison name as well as code is required.

Extend bank_admin API to provide additional information

---

mtp_api/apps/transaction/api/bank_admin/urls.py
mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/urls.py

In the previous configuration, the route for refunding transactions
was being set to /transactions/patch_refunded rather than the
intended /transactions/.

Correct the URL used for refunding transactions

---

mtp_api/apps/prison/urls.py

As slumber works by converting the attributes of the client object
that are accessed into the URL, and an attribute cannot contain a
hyphen, we must change the URL to contain an underscore instead.

Change prisoner locations endpoint URL for slumber compatibility

---

mtp_api/apps/prison/serializers.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/tests/utils.py
mtp_api/apps/transaction/api/bank_admin/serializers.py
mtp_api/apps/transaction/api/cashbook/views.py
mtp_api/apps/transaction/managers.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/signals.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/test_cashbook_views.py
mtp_api/apps/transaction/tests/test_prison_updates.py
mtp_api/apps/transaction/tests/utils.py

This changes the logic behind the Transaction.prison field.
When new transactions get uploaded and created, they don't have the the notion of 'assigned prison'. This information is in an extra file called *prisoner location upload* containing a list of (prisoner_number, prisoner_dob, prison).
The actual prison of a transaction is the left outer join between the tables `transaction` and `prisoner location` on `(prisoner_number, prisoner_dob)`.
I tried changing the queries so that the prison would be calculated by executing the above join every time but it wasn't working well so we decided to pre-calculate the prison and store it in the `Transaction.prison` field instead.
As transactions and prisoner location records are created at different times though, it was hard to determine when to …

Transaction.prison updated from prisoner location upload

---

requirements/base.txt
requirements/dev.txt

This was previously only included in the dev requirements, but is
required if we wish to be able to load test data automatically as
a docker task.

Add mommy_recipes to base requirements

---

mtp_api/apps/prison/fixtures/test_prisons.json
mtp_api/apps/prison/migrations/0005_prison_general_ledger_code.py
mtp_api/apps/prison/models.py
mtp_api/apps/prison/serializers.py
mtp_api/apps/transaction/api/bank_admin/serializers.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py

Phoenix uses a different code to identify prisons to NOMIS,
so this code, the general ledger code, must also be recorded
in the database and returned by the API for the purpose
of reconciliation with Phoenix.

Add general_ledger_code field to prison table

---

mtp_api/apps/mtp_auth/serializers.py
mtp_api/apps/mtp_auth/tests/test_views.py

Add the user's object permissions to the response body
of the user lookup endpoint in order to allow front-end
applications to control display of actions that the user
can perform.

Return the user's permissions in the user data response

---

mtp_api/apps/core/tests/utils.py
mtp_api/apps/prison/migrations/0006_prisonerlocation_prisoner_name.py
mtp_api/apps/prison/models.py
mtp_api/apps/prison/tests/utils.py
mtp_api/apps/transaction/api/cashbook/serializers.py
mtp_api/apps/transaction/managers.py
mtp_api/apps/transaction/migrations/0013_transaction_prisoner_name.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/tests/test_prison_updates.py
mtp_api/apps/transaction/tests/utils.py

Add prisoner name (sourced from the prisoner location upload) to the models. Will be included in the list of transactions received by the cashbook application.
Bonus commit: make two test clerks per prison.

Add prisoner name

---

mtp_api/apps/core/management/commands/load_test_data.py
mtp_api/apps/core/tests/utils.py
mtp_api/apps/mtp_auth/migrations/0003_applicationusermapping.py
mtp_api/apps/mtp_auth/models.py
mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/mtp_auth/validators.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/transaction/tests/test_base.py
mtp_api/settings/base.py

This means that only users which has been explicitly linked to
a particular application (e.g. bank admin, cashbook) can authenticate
with that client. This means that a prison clerk cannot log in to
bank admin (unless they have been allowed to).
Uses a new table mtp_auth_applicationusermapping to store the mapping
of users to applications which they can log in to.

Only allow users associated with a client to log in to it

---

docker_entrypoint.sh

The flush command operates on an explicit list of table so if the
tables defined in the application is different to those present
in the db it will fail. For this reason a migrate must be run
before the flush command to ensure that the db data model matches
that of the application.

Run a migrate task before attempting to flush when resetting db

---

mtp_api/apps/transaction/api/bank_admin/serializers.py
mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/constants.py
mtp_api/apps/transaction/managers.py
mtp_api/apps/transaction/migrations/0014_auto_20151013_1113.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/signals.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/utils.py

This consists of a new field, reconciled, which is orthogonal to
the status of the transaction. It is now possible to filter by
this field when querying the bank_admin endpoint. A new Log record
is created whenever a transaction is reconciled, which is done
by a patch request to the bank_admin transaction endpoint.

Add reconciliation tracking to transaction model

---

mtp_api/apps/mtp_auth/fixtures/initial_groups.json
mtp_api/apps/transaction/api/bank_admin/permissions.py
mtp_api/apps/transaction/api/bank_admin/urls.py
mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/migrations/0015_auto_20151019_1430.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py

This change allows all bank admins to make updates to transactions,
to allow for the need for non-refund bank admins to update transactions
that have been reconciled.

Update permissions for bank admin updating transactions

---

mtp_api/apps/account/admin.py
mtp_api/apps/account/fixtures/initial_file_types.json
mtp_api/apps/account/migrations/0001_initial.py
mtp_api/apps/account/migrations/0002_auto_20151102_1143.py
mtp_api/apps/account/models.py
mtp_api/apps/account/serializers.py
mtp_api/apps/account/tests.py
mtp_api/apps/account/tests/test_views.py
mtp_api/apps/account/urls.py
mtp_api/apps/account/views.py
mtp_api/apps/core/management/commands/load_test_data.py
mtp_api/apps/mtp_auth/fixtures/initial_groups.json
mtp_api/settings/base.py
mtp_api/urls.py

This is to:
a) enable someone to re-download a copy of the same file (or rather a file including the same set of transactions)
b) track which transactions have already been downloaded for the purpose of creating files from 'all matching transactions which have not yet been included in a file of this type'
The latter will acquire additional work in the API to implement but I'm trying to do smaller PRs.
I might also retire the 'processed' flag as a result of this change, as its sole functionality would be accomplished by b).

File download tracking

---

mtp_api/apps/mtp_auth/tests/mommy_recipes.py

to allow for integration tests to expect more specific details (currently login cucumber test in cashbook fails because the name varies)

Ensure users' names generated for random test data are more consistent

---

docker_entrypoint.sh

As these are run by a script, cannot rely on user input.
Will rely on humans to clean up any issues.

Add --noinput flag to setup management commands

---

mtp_api/apps/account/migrations/0004_auto_20151110_1038.py
mtp_api/apps/account/models.py

Although we do want to enforce shorter labels, the previous
length was overly restrictive.

Increase the max length of the label field on batch records

---

mtp_api/apps/mtp_auth/admin.py
mtp_api/apps/mtp_auth/migrations/0004_failedloginattempt.py
mtp_api/apps/mtp_auth/models.py
mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/mtp_auth/validators.py
mtp_api/settings/base.py

for half an hour if there are 5 failed attempts ever

Prevent brute force login attacks by locking user accounts

---

mtp_api/apps/transaction/api/bank_admin/urls.py
mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/constants.py
mtp_api/apps/transaction/managers.py
mtp_api/apps/transaction/migrations/0017_auto_20151125_1040.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/signals.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/test_prison_updates.py

The purpose is that after a reconciliation file for a particular day has been downloaded,
all transactions for that day should be marked as reconciled and no longer be updated
by subsequent uploads of the prisoner location file.

Track reconciliation

---

mtp_api/apps/transaction/api/bank_admin/views.py

This is required as we use the select_for_update() method.

Perform reconciliation update within a transaction

---

mtp_api/apps/core/management/commands/delete_all_data.py
mtp_api/apps/core/management/commands/load_test_data.py
mtp_api/apps/core/tests/test_admin.py
mtp_api/apps/core/views.py

mainly to ensure transaction-uploader always has a user account that won't get deleted even in non-prod environments

Enable test data reset tools prevent deletion of specified users

---

mtp_api/settings/base.py
mtp_api/urls.py
requirements/base.txt

depends on [django-moj-irat#1](https://github.com/ministryofjustice/django-moj-irat/pull/1)

Add a healthcheck.json view for IRaT support which tests database connectivity

---

mtp_api/settings/base.py

• all logs are prepended with their level
• all logs of level INFO or higher will be output to the console and ELK
• all logs of level ERROR or higher will also be sent to Sentry if configured

Make django logging consistent between apps

---

mtp_api/apps/transaction/tests/utils.py

This is to match the transactions uploaded from the bank
statement, which will not include any time information.

Set received_at date of test transactions to have zero time

---

Dockerfile
Makefile

because Jenkins job wants these to exist before deployment so it can put them on S3
(aside: no clear idea why we use S3 to store assets as nginx proxies them back)

Collect static files as well as updating python requirements earlier in build process

---

mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py

This may be wrong, but until we know how we will reconcile
online payments it is probably for the best.

Fix ref_code generation to only consider bank transfers

---

mtp_api/apps/core/management/commands/load_test_data.py
mtp_api/apps/transaction/admin.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/test_base.py
mtp_api/apps/transaction/tests/test_cashbook_views.py
mtp_api/apps/transaction/tests/utils.py

For certain forms of testing, it is better that the test data
not cover all possible scenarios, but instead cover the business
as usual scenario. This means that test data should be historically
consistent i.e. all transactions processed up to the last weekday,
no old transactions that are further processed than newer ones etc.
This will also exclude administrative transactions and online
payment transactions.

Improve test data

---

mtp_api/apps/core/management/commands/delete_all_data.py
mtp_api/apps/core/management/commands/load_test_data.py

Leaving the balance records resulted in erroneous opening and
closing balances in the BAI files.

Delete all balance records when transactions are reset

---

mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/test_cashbook_views.py
mtp_api/apps/transaction/tests/utils.py

Transactions in the DB are stored with a recevied_at date with a UTC
timezone, and date params parsed by django-reset-framework are similarly
given a UTC param. In places where this parsing is done in our code,
we have been using the current timezone instead, leading to inconcistencies
and incorrect behaviour. This fixes any manual parsing of a pure date into
a datetime to use the UTC timezone.

Use UTC when manually parsing dates, to match TZ used by default

---

mtp_api/apps/core/forms.py
mtp_api/apps/core/management/commands/load_test_data.py
mtp_api/apps/core/tests/test_admin.py
mtp_api/apps/core/views.py

When creating test transactions via management command or admin
interface, it should be possible to specify the number of transactions
that will be created.

Allow for creation of variable number of test transactions

---

mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/test_cashbook_views.py
mtp_api/apps/transaction/tests/utils.py

Use the default timezone where datetimes are parsed explicitly,
to match that employed by library methods and functions.
This is just to make sure that times are treated consistently, in
advance of discussing how to treat times.

Ensure consistent use of configured timezone

---

mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py

Previously, each time a reconciliation file was downloaded,
another reconciliation log record was created for each transaction
in the file.

Prevent reconciliation events being logged multiple times

---

mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/managers.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/utils.py

This is due to the existence of unidentified transactions - those
which cannot be credited or refunded. As whether or not a transaction
can be credited is not known at the time of creation, we need to defer
the creation of ref codes until the point of reconciliation, after which
we know that the validity of the transaction will not change.

Create ref codes on reconciliation instead of creation

---

mtp_api/apps/transaction/api/bank_admin/views.py
mtp_api/apps/transaction/api/cashbook/views.py
mtp_api/apps/transaction/pagination.py
mtp_api/apps/transaction/tests/test_bank_admin_views.py
mtp_api/apps/transaction/tests/test_cashbook_views.py
mtp_api/settings/base.py

to allow cashbook to not require filtering by date in history view (and still mitigate against overly-long pages)

Add date-based pagination to cashbook transaction list view

---

mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/mtp_auth/views.py

Deactivate instead of destroying users deleted by user admin. This is to preserve the audit trail.

Deactivate users

---

mtp_api/apps/mtp_auth/views.py

Django rest framework errors are returned as lists per field as
standard.

Return the user self-deletion error as a list to match standard

---

mtp_api/apps/core/dashboards.py
mtp_api/apps/core/views.py
mtp_api/apps/transaction/dashboards.py

so they're not displayed arbitrarily depending on module loading order

Make dashboard modules have a priority order

---

mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/mtp_auth/views.py

Users can be created with full stops in their names and thus
it should be possible to query them.

Allow path username parameter to include full stops

---

mtp_api/apps/transaction/managers.py

Earlier transactions will consistently have a lower ref code.

Make the ordering of ref codes assigned to transactions consistent

---

mtp_api/apps/transaction/models.py

There are a variety of states which will never arise but which
we nevertheless check for. This is defensive verging on the
superstitious, and is unnecessary.

Simplify the status lookup to remove impossible conditionals

---

mtp_api/apps/mtp_auth/admin.py

since there are no existing migrations or fixtures to create them automatically

Allow application-to-group mappings to be edited in Django admin

---

mtp_api/apps/credit/admin.py
mtp_api/apps/credit/constants.py
mtp_api/apps/credit/models.py
mtp_api/apps/transaction/admin.py

The credit model is now more relevant than transactions for
examination of data, and as such much of the functionality added to
the transaction admin has been moved to the credit admin.

Implement credit admin functionality for support and analysis

---

mtp_api/apps/core/filters.py
mtp_api/apps/credit/views.py
mtp_api/apps/transaction/tests/test_views.py
mtp_api/apps/transaction/views.py

The specialised filter for transactions is no longer needed, so
it can now share the same status filter as the cashbook API.

Use the same status choice filter for credits and transactions

---

mtp_api/apps/core/__init__.py
mtp_api/apps/credit/serializers.py
mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/urls.py
mtp_api/apps/credit/views.py

The switch to SQL is due to the fact that there is not much benefit
to using django ORM in this case, and it is arguably easier to
understand in this form.

Add recipient endpoint and use SQL for recipient and sender

---

mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/views.py

There was an error whereby the minimum/maximum limits on the number
of senders/receivers on the security credit endpoints were not being
honoured in the case where there were filters applied to the base
queryset.

Fix use of minimum counts with other filters on security endpoints

---

mtp_api/apps/mtp_auth/serializers.py
mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/urls.py
mtp_api/apps/prison/views.py

Additionally, cease returning a list of prison IDs as part of the
authentication information as it is not used.

Add a prison endpoint to retrieve prisons a user can access

---

mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/tests/utils.py
mtp_api/apps/credit/views.py
mtp_api/apps/payment/tests/utils.py
mtp_api/apps/transaction/tests/utils.py

This filtering can be on magnitude or on certain patterns such
as the least significant digits of a regex. These two pattern
types can also be excluded from the result set.

Add filtering on the amount of a credit for intelligence analysis

---

mtp_api/apps/credit/forms.py
mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/views.py

Return a tuple of query string and param list from Form SQL filter
constructor rather than returning a query string with the params
inserted. Also return a tuple from View SQL filter constructor
to avoid mutation of param list variable.

Refactor raw SQL generation to avoid direct param insertion

---

mtp_api/apps/mtp_auth/views.py

If the lazy version is used then the subject line is formatted
incorrectly when sending an email via mailgun.

Use non-lazy gettext for translating email subject line

---

mtp_api/apps/core/filters.py
mtp_api/apps/credit/admin.py
mtp_api/apps/credit/managers.py
mtp_api/apps/credit/models.py
mtp_api/apps/credit/views.py
mtp_api/apps/transaction/admin.py
mtp_api/apps/transaction/dashboards.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/serializers.py
mtp_api/apps/transaction/tests/test_dashboard.py
mtp_api/apps/transaction/tests/test_views.py

This allows for more flexibility in status definitions e.g.
OR as well as AND, subclauses etc.

Use Q objects instead of dictionaries to build status filters

---

mtp_api/apps/credit/serializers.py

This is to allow the display of anonymous credits in the
cashbook history screen (where it was possible to identify
the prisoner).

Add 'anonymous' field to credit serializer

---

mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/views.py

Allow for specifying a null prison as a credit filter, and order returned
subsets of grouped queries, with null values coming last.

No prison filtering

---

mtp_api/apps/core/management/commands/testserver.py
mtp_api/apps/core/tests/test_permissions.py

so that email sending functions can filter these out and not flood MailGun with errors

Make all test email addresses @mtp.local or @outside.local

---

mtp_api/settings/base.py

…so that client app session times can be set to match this value

State explicitly how long sessions and access tokens are valid for in settings

---

mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/mtp_auth/validators.py

If a user attempts to access a client application which they do not
have permission to access, a 403 response will be returned rather
than a 401. This is to allow us to handle error messaging to the
user differently.

Return a forbidden response for login attempt in disallowed application

---

mtp_api/apps/credit/models.py
mtp_api/apps/credit/tests/test_base.py
mtp_api/apps/credit/views.py
mtp_api/apps/transaction/models.py
mtp_api/apps/transaction/tests/test_views.py
mtp_api/apps/transaction/tests/utils.py

Any payment which has incomplete sender information will no longer
be credited to a prisoner, even if it is possible to identify the
prisoner for whom it is intended. Instead it will be classified as
an 'unidentified' payment and no automatic action will be taken.
Payments lacking sender information which have been credited in the
past will still show up as successful payments.

Reject anonymous payments

---

mtp_api/apps/account/serializers.py
mtp_api/apps/account/tests/test_views.py
mtp_api/apps/account/views.py
mtp_api/apps/credit/managers.py
mtp_api/apps/mtp_auth/fixtures/initial_groups.json
mtp_api/apps/transaction/constants.py
mtp_api/apps/transaction/managers.py
mtp_api/apps/transaction/models.py

* Allow for a batch to be updated after intial creation
* This means that not all transactions have to be included in the create request, allowing for batching of large numbers of transactions.
* Optimise the reconciliation of transactions
* Process credits and transactions separately
* Bulk update credits to reconciled, and bulk create credit reconciliation
logs
* Use temp table insert to do bulk update of generated ref codes on
transactions

Optimisations

---

mtp_api/apps/prison/serializers.py

This is to make the problem more obvious in cases where the uploaded
location file contains prisons which are not known to the MTP system.

Improve error message for prison not found in location file upload

---

README.md

The rest of the readme and the configuration in other apps
expects the docker VM to be named 'default', not 'dev'.

Fix docker-machine VM name to be consistent

---

mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/views.py

Previously the credit endpoint used received_at_0, received_at_1 and
the transaction endpoint used received_at_gte, received_at lt. They
now both use gte/lt.

Make the received_at range filter syntax consistent between endpoints

---

mtp_api/apps/transaction/tests/test_views.py

This is due to the fact that as the data is less random now
it is reasonably possible for there to be several test transactions
with the same parameters.

Change test check from exactly one result to existence

---

mtp_api/apps/credit/managers.py
mtp_api/apps/credit/tests/test_prison_updates.py
mtp_api/apps/credit/tests/test_views.py

As debit card refunds need to be reconciled manually, we cannot track
such refunds within our system. If an update to prisoner locations will
mean that a previously matched debit card payment will no longer be
creditable, do not update that payment's corresponding credit. Instead it
will remain assigned to the last matched prison.

Avoid setting prison to null on a debit card payment

---

mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/views.py

• this allows a client to provide a subset of prisons to search
• the exact prisoner location is still not revealed to client

Allow filtering by prison id when looking up if a prisoner location is valid

---

mtp_api/apps/payment/serializers.py
mtp_api/apps/payment/tests/test_views.py

The resolution of a credit newly created for a debit card payment
should be 'initial' until the payment has been captured, at which
point it should switch to 'pending'.

Newly created credits for debit card payments should be 'initial'

---

mtp_api/apps/core/management/commands/delete_zendesk_tickets.py
mtp_api/settings/base.py

We clead up older, closed tickets in order to avoid keeping
potentially personal information in zendesk longer than strictly
necessary.

Add command to delete zendesk tickets older than two weeks

---

mtp_api/apps/core/filters.py
mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/transaction/tests/test_views.py

Now only tried to parse as an ISO format datetime once,
rather than in every iteration of the parsing attempt loop.

Add tests and improve ISO datetime filter

---

mtp_api/apps/mtp_auth/forms.py

Otherwise we get a 500 if the passwords don't match.

Replace password_mismatch error message in override of user creation form

---

mtp_api/apps/credit/dashboards.py
mtp_api/templates/core/dashboard/credit-report-cells/error-rate.html

Card payment error rates cannot be accurately portrayed.

Only include bank transfers in dashboard error rate

---

mtp_api/apps/core/management/commands/run_scheduled_commands.py

It is quite likely that a command will not be run due to a database lock,
and is this not necessarily a big deal.

Downgrade concurrent scheduled command exception log to warning

---

mtp_api/apps/credit/serializers.py

This gives cashbook users visibility of the sender email, which
is used to send a confirmation of crediting to the sender.

Include email in base credit serializer

---

mtp_api/apps/prison/serializers.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/settings/base.py

This is to inform send-money about different behaviour that needs
to be used for prisoners who are in prisons where NOMIS integration
has been rolled out.

Add nomis integration flag to prisoner validity check

---

mtp_api/apps/core/admin.py
mtp_api/apps/core/models.py
mtp_api/apps/credit/admin.py
mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/views.py
mtp_api/apps/transaction/pagination.py

Bank admin gets credits by UTC date, as it needs to match the
batching used by Worldpay. The cashbook thus needs to display
data from dates prior to the current UTC date.

Ensure that date boundary in cashbook matches that of bank admin

---

mtp_api/apps/credit/admin.py
mtp_api/apps/payment/admin.py

Credit and payment had drop down selections for related objects
which involved a very long list.

Speed up dmin page rendering by not loading massive drop downs

---

mtp_api/apps/credit/admin.py

This is to avoid slow loading and poor page performance from a
very large select drop-down.

Make billing address read only on inline payment in credit admin

---

api.ini

This is to allow for the longer query params used when querying
the status of a processing batch.

Increase buffer size to allow for longer url params

---

mtp_api/apps/core/forms.py
mtp_api/apps/core/management/commands/load_data_listener.py
mtp_api/apps/core/management/commands/testserver.py
mtp_api/apps/core/views.py
mtp_api/apps/transaction/tests/utils.py

Cashbook smoke tests rely on the generation of dev NOMIS compatible
prisoner locations. Also remove no longer relevant test data scenarios.

Allow for the generation of alternative test data for smoke tests

---

mtp_api/apps/mtp_auth/serializers.py
mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/mtp_auth/views.py
mtp_api/templates/mtp_auth/create_new_password.html
mtp_api/templates/mtp_auth/create_new_password.txt

If the client app were to send the email, there would need to be an
unauthenticated endpoint to retrieve a user's email address, which
would be bad.
Adds new fields to the request to specify the URL format of the
client app's password reset page.

Change password reset with code to send the email on the API side

---

mtp_api/apps/core/management/commands/run_scheduled_commands.py

This will prevent a failing scheduled command from stopping others
to run.

Catch errors for scheduled commands

---

mtp_api/apps/service/migrations/0005_notification_levels.py
mtp_api/apps/service/models.py

it was previously dependent on volatile dictionary order

Stabilise notification level ordering

---

mtp_api/apps/transaction/views.py

This is predominantly for the purposes of manually generating corrective
reconciliation files when necessary.

Allow for querying of transactions by pk

---

mtp_api/apps/disbursement/serializers.py

Otherwise can get errors if disbursements are processed whilst
locations are being updated.

Only check active prisoner locations for disbursement operations

---

mtp_api/settings/base.py
requirements/dev.txt
requirements/docker.txt

As the API is unavailable from the public internet, assets in e.g. emails
sent by the API were not available.

Set a public static url for assets in places that cannot access the API

---

mtp_api/apps/disbursement/managers.py
mtp_api/apps/disbursement/models.py
mtp_api/apps/disbursement/tests/test_views.py
mtp_api/apps/disbursement/tests/utils.py

If we do not generate the invoice number until the disbursement is sent
it is not available for inclusion in the disbursements file.

Generate disbursement invoice number on confirmation as sent is too late

---

mtp_api/apps/disbursement/admin.py

This is to avoid lengthy load times when viewing these pages.

Set profile fields to read-only on disbursement admin page

---

mtp_api/apps/credit/views.py
requirements/base.txt

This allows cashbook users to search payments using the reference
numbers that users get after making a payment.

Add payment UUID to credit text search filter

---

mtp_api/apps/mtp_auth/fixtures/initial_groups.json

…they too need to reconcile and load private estate batches

Ensure disbursement-only bank admins can download disbursements file

---

mtp_api/apps/notification/management/commands/send_notification_emails.py

Had an extraneous forward slash in it.

Fix the link to the notifications page in the notifications email

---

mtp_api/apps/mtp_auth/views.py

They were previously on the field 'username', which was not
working as the form that attempts to display the error does
not have a 'username' field.

Change errors in account confirmation to non-field errors

---

mtp_api/apps/notification/views.py

This is to allow for the display of only one event where
it has been triggered by e.g. both a monitored prisoner
and a monitored bank account.

Allow for monitored events to be grouped by record

---

mtp_api/apps/payment/managers.py

When reconciling payments, a payment batch object is created and
all payments in the batch are assigned to it. We use select_for_update
on the set of payments that will comprise this batch in order to
avoid interleaving operations, however as we did not evaluate the
queryset before creating the payment batch, this was resulting in new
payment batches being created which then didn't have any payments in.
By changing the conditional from a `count()` to a `len()` this ensures
that the update set is evaluated and a lock acquired before the payment
batch record is created, which should avoid superfluous payment batches
being made.

Prevent the creation of empty payment batches due to race condition

---

mtp_api/apps/core/filters.py
mtp_api/apps/core/tests/test_filters.py
mtp_api/apps/security/tests/test_views.py
mtp_api/apps/security/views.py

The `/senders/` endpoint was updated to support a new search param called `search` which filters senders by:
```
the sender name of the a transfer bank details object 
OR 
the cardholder name of a debit card details object 
OR 
the sender email of a debit card details object
```

Add ability to search senders using the 'search' filter

---

mtp_api/apps/credit/tests/test_views.py
mtp_api/apps/credit/views.py

This adds a new `simple_search` search param to the credit list view which makes an icontains lookup on multiple text fields.
It's different from the `search` field which is more sophisticated and searches across more fields of different types.
@ushkarev I've decided not to parse the prisoner_number as I don't think the change in performance is big enough to justify the added complexity. Even if the text inputted by the user matches a prisoner number, we would still need to run ICONTAINS in OR on the other fields in case the same text appears in other places. Therefore, we would only save one ICONTAINS (which would be replaced by an IEXACT) which is minimal in my opinion.

Add simple_search search param to credit list view

---

mtp_api/apps/security/tests/test_views.py
mtp_api/apps/security/views.py

Credits uses already a `search` param which acts a bit differently to what we need here.
This renames the senders `search` param to `simple_search` so that we can use that name consistently for all object types.

Rename senders search param to simple_search

---

mtp_api/apps/core/filters.py
mtp_api/apps/core/tests/test_filters.py
mtp_api/apps/credit/views.py
mtp_api/apps/disbursement/tests/test_views.py
mtp_api/apps/disbursement/views.py

This:
- moves PostcodeFilter to core app
- adds tests for PostcodeFilter
- replaces disbursements postcode filter field with PostcodeFilter
- refactor disbursements tests so that they test more scenarios and further scenarios can be easily added

Use PostcodeFilter in disbursements filtering

---

mtp_api/apps/security/serializers.py
mtp_api/apps/security/tests/test_views.py
mtp_api/apps/security/views.py

This:
1. Adds `prisons` to `GET /senders/` response
2. Adds a new `current_prison` filter to the `GET /prisoners/` endpoint so that clients can filter by one or more values.

Prison filter in advanced search

---

mtp_api/apps/notification/management/commands/send_notification_emails.py
mtp_api/templates/notification/not-monitoring.html
mtp_api/templates/notification/not-monitoring.txt
mtp_api/templates/notification/notifications.html
mtp_api/templates/notification/notifications.txt

This adds GA campaign settings to notification emails.
It depends on https://github.com/ministryofjustice/money-to-prisoners-common/pull/356.
Also, the noms-ops application needs the version of mtp-common with the change in PR 356.

Add GA campaign settings to notification emails

---

mtp_api/apps/notification/management/commands/send_notification_report.py
mtp_api/apps/notification/rules.py
mtp_api/apps/notification/tests/test_commands.py
mtp_api/apps/notification/tests/test_rules.py
mtp_api/apps/notification/tests/utils.py

e.g. if the ‘How many?’ column says 6 for the rule ‘More than 4 credits from the same debit card or bank account to any prisoner in 4 weeks’, then this means that a specific debit card or bank account got 6 credits in 4 weeks up to when that credit was sent.

Show counts for matching counting rules in notification report

---

mtp_api/assets-src/stylesheets/app-ie8.scss
mtp_api/assets-src/stylesheets/app.scss
mtp_api/settings/base.py
requirements/dev.txt
requirements/docker.txt

This adds the cloud platform migration middleware and sets up the related settings values as env vars.
@ushkarev :
1. I had to add `app.scss` and `app-ie8.scss` as the page looked broken otherwise (the compiled versions are loaded by `mtp_base.html`). What do you think?
2. `mtp_base.html` also looks for `app.bundle.js` and `app-print.css` which 404. I guess it's not a problem?

Add support for cloud platform migration

---

mtp_api/apps/service/migrations/0007_notification_areas.py
mtp_api/apps/service/models.py

This adds a new send_money_landing target for notifications to appear on the landing page of the send money service.
I've changed the migration file directly as there's no database change so having a new file for this change is a bit of a waste.
I've only added an area for the landing page, not sure if we want one for all pages as well?

Add new notification target for Send Money

---

api.ini

it was used for functional tests running on jenkins, but on prod, this daemon is constantly being relaunched and possibly degrades performance

Turn off uwsgi "load data listener" daemon

---

api.ini
requirements/base.txt

… in the hope of making it work better with keep-alive/connection pooling issues that originate in urllib3.
also:
- simplify logging (CP kibana does not expand json logs into fields)
- add uwsgi stats server (only available inside container)
- hopefully improve k8s/docker compatibility

Update uWSGI options

---

mtp_api/apps/credit/serializers.py

which is the time a user was on the website (i.e. at ip address)

Add payment started time to api output

---

.circleci/config.yml
.github/CODEOWNERS
Dockerfile
README.md
mtp_api/settings/base.py
mtp_api/urls.py
requirements/dev.txt
requirements/docker.txt

- As apps are now able to discover each other, many environment variables are now redundant so they can be removed
- Apps now use base Docker images built by this repository (pulling from ECR or building locally) – this speeds up builds and ensures they have the same base OS
- Add prometheus service monitors for all apps
- Depends on [mtp-deploy#282](https://github.com/ministryofjustice/money-to-prisoners-deploy/pull/282)

Remove template-deploy artefacts

---

mtp_api/apps/security/tests/test_views.py
mtp_api/apps/security/views.py

So that we can exclude the ones related to credits not in initial resolution state.

Add credit_resolution filter to check list endpoint

---

mtp_api/apps/core/management/commands/dump_for_ap.py
mtp_api/apps/core/tests/test_dump_for_ap.py

In working with the `dump_for_ap` and uplaoding the results of the
export command, we ran into problems with the last 8kb of the exported
data remaining in the buffer when the file was worked with in the
command itself.
Although the final implementation will not be called while any export
data remains in the buffer, this was an unexpected complexity that could
be avoided.
Given that a `with` block closes a file when its finished, we think this
simplifies the export itself. Removing the `argsparse.FileType` however
meant that we didn't have ahook to stdout, so the tests had to update
to use temporary files.
This should also make the conversion to a JSON Lines format easier, as
we need to work with the data export without `csv.DictWriter` help.

Refactor file handling in Analytical Platform dump

---

mtp_api/apps/core/management/commands/dump_for_ap.py
mtp_api/apps/core/tests/test_dump_for_ap.py

This change is converting the previous data format of CSV to JSON Lines[1] as requested by the data team.
The change simplifies the code a little bit following the previous refactor (#583).
- Should we worry about any previous data breaking the JSON encoding?
- Will all systems that we are exporting to use the right EOL sequence (i.e. will `\n` work in all environments this code will run on?)
1. http://jsonlines.org/

Convert output file to JSON Lines format

---

mtp_api/apps/credit/serializers.py
mtp_api/apps/security/tests/test_views.py

Change date format helper to use utc in tests
Jira: https://dsdmoj.atlassian.net/browse/MTP-1402
The `format_date_or_datetime` helper broke tests when the UK shifted to
BST, with a time offset. This meant that the Serializer returned a
formatted string including the offset hours, which didn't match the
actual date returned inthe JSON formatted check, as that remained a UTC
string.
The timezone of the dates for the test data is utc, however in the util
`format_date_or_datetime` used the django detected London timezone
in the serializer `to_representation`.
To ensure that the dates are comparative, we can set the timezone in the
utiity serializer call.
AND
Use isoformat() to retain timezone info
The filter tests started failing *really* regularly due to the
`strftime` dropping time zone …

Account for British Summertime in tests

---

mtp_api/apps/credit/admin.py

This a change to makle the variable name appease flake8 mainly, but a
good change to make anyway.
Flake8 on https://app.circleci.com/pipelines/github/ministryofjustice/money-to-prisoners-api/511/workflows/0b0a1e75-2129-483b-b674-8b220c90eacc/jobs/600 failed, despite branches passing. Weird, but need to sort it quick

Update log variable name

---

mtp_api/apps/prison/serializers.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/urls.py
mtp_api/apps/prison/views.py

[MTP-1465/MTP-1477](https://dsdmoj.atlassian.net/browse/MTP-1477)
- private cash, spends and savings account balances are combined into one total "combined_account_balance"
- balances are not available in private estate so 0 is returned; send-money will effectively ignore current balance
- errors from NOMIS are propagated to client

Allow send-money app to read combined account balances from NOMIS

---

mtp_api/apps/payment/tests/test_views.py
mtp_api/apps/security/admin.py
mtp_api/apps/security/managers.py
mtp_api/apps/security/migrations/0029_remove_check_description_prefix.py
mtp_api/apps/security/migrations/0030_migrate_check_description.py
mtp_api/apps/security/models.py
mtp_api/apps/security/tests/test_checks.py
mtp_api/apps/security/tests/test_views.py

…so that the description can be appropriately labelled depending on where it is displayed.
[MTP-1488](https://dsdmoj.atlassian.net/browse/MTP-1488)

Remove “Credit matched: ” prefix from security check description

---

Dockerfile
mtp_api/templates/mtp_common/build_tasks/docker-compose.yml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/docker.txt
run.py

Simplify python dependency tree by installing the correct version of mtp-common on _first run_ (i.e. when none is installed). This subsumes the dependencies for a production/deployed image into the base requirements which also simplifies testing.
Depends on [mtp-common#401](https://github.com/ministryofjustice/money-to-prisoners-common/pull/401)

Simpler python dependency tree

---

mtp_api/apps/security/admin.py

A `SenderProfile` can have a `BankTransferSenderDetails` (when it's the
sender for a bank tranfer). This model has a `sender_name` field.
(the sender name was previously searched in the `BankAccount` model which
doesn't have a `sender_name` field)
Sentry exception: https://sentry.io/organizations/ministryofjustice/issues/2129937552/?project=2098210&project=2100450&project=2100423&project=2100458&project=2100467&project=2100463&query=is%3Aunresolved+assigned%3Ame&statsPeriod=14d
Part of ticket: https://dsdmoj.atlassian.net/browse/MTP-1773

admin: Fix search of sender profiles

---

mtp_api/apps/disbursement/admin.py

By allowing user to search disbursements also by NOMIS transaction ID
or by Invoice Number.
In addition to these fields being searched, the Invoice Number is now
shown in the table as well as this is useful.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1774

admin: Improve disbursements search

---

mtp_api/apps/credit/admin.py

These fields were editable which meant when seeing a Credit details
they were pulling extra data to populate the selects.
This page is used in a read-only fashion so these fields are now read-only
to speed-up the loading time of this page.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1800

admin: Credit details, make owner and private_estate_batch R/O

---

.circleci/config.yml
.circleci/custom_scripts/run_checks.sh
.circleci/custom_scripts/start_db_container.sh

Running some Django checks as part of our CI build pipeline:
- `./manage.py checks` and
- `./manage.py makemigrations --check` which would return a non-zero status when new migrations were generated. e.g. potentially we forgot to run `makemigrations` and we didn't include them
This additional `run_checks` job will run alongside the `test` job as it should be relatively fast and it's useful to know as soon as possible if we missed something in a PR for example.
**NOTE**: Also note that this would not block push of the docker image or deploy to test.
The assumption is that sometimes it may make sense to temporarily leave some DB schema changes/migrations out of a PR.
If we later on decide this checks should be blocking we can always change the CI workflow to be more draconian.
Ticket: …

CI: Run Django checks and check if code misses migrations

---

mtp_api/apps/security/migrations/0031_check_rejection_reasons.py

to match change made in commit: aabb048cb409a9622496c15baee1862212ce5173
This has no effect on the database fields in postgres so a fix-up to an old migration is valid; it's not necessary to make a new migration and deploy.
So now CI ~should be~ is happy that migration files match models.

Fix migration

---

mtp_api/apps/mtp_auth/tests/mommy_recipes.py
mtp_api/apps/security/serializers.py
mtp_api/apps/security/tests/test_checks.py
mtp_api/apps/security/tests/test_views/test_check_views.py
mtp_api/apps/security/tests/utils.py
mtp_api/apps/security/views.py
requirements/dev.txt

Jira: https://dsdmoj.atlassian.net/browse/MTP-1734
Related PRs
noms-ops:  https://github.com/ministryofjustice/money-to-prisoners-noms-ops/pull/512
TODO

MTP-1734 auto accept lists

---

mtp_api/apps/core/forms.py
mtp_api/apps/core/management/commands/load_test_data.py
mtp_api/apps/core/views.py
mtp_api/apps/prison/fixtures/dev_prison_api_prisons.json
mtp_api/apps/prison/tests/test_utils.py
mtp_api/apps/prison/tests/utils.py

This scenario generates PrisonerLocation for prisoners present in the
`dev` version of HMPPS Prison API.
Limitations
-----------
This scenario relies on few well known prisons being present in the
`dev` api. There isn't an endpoint to get a list of prisons so this may
break in the future if these prison are removed from `dev`.
Refactorings
------------
I've also used this opportunity to tidy up `RecreateTestDataView` and
moved the various scenarios configuration in a dictionary and removed
the long `if`/`elif` chain.
See
---
HMPPS Prison API documentation: https://api.prison.service.justice.gov.uk/swagger-ui/index.html
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1490

Add dev-prison-api scenario to load_test_data

---

requirements/base.txt
requirements/dev.txt

This is using a newer version of `mtp-common` (`11.1.0`).
⚠️ **NOTE**: as we bump from `10.x` to `11.x` and that new version contains some other changes (e.g. GDS design system changes) - this probably need some coordination before we merge it.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1537

MTP-1537: Move dependencies in mtp-common

---

mtp_api/apps/core/tests/test_swagger.py
mtp_api/apps/security/views.py

Whilst developing against MTP-1805, I realized the `CheckAutoAcceptRuleView` endpoint had broken swagger because there were two `ordering` parameters; one provided by `filters.OrderingFilter` and one provided by `CheckAutoAcceptRuleFilter`. Since the former can't filter on related fields, and was being overridden by the latter I removed the former.
I also added a simple test to spot this issue if it occurs again. I put it in `core/tests/` for lack of a better place, but i'm open to moving it

Fixed duplicate parameter error in swagger without impacting production functionality

---

api.ini
mtp_api/apps/performance/forms.py
mtp_api/apps/performance/management/commands/update_performance_platform.py
mtp_api/apps/performance/migrations/0004_retire_performance_platform.py
mtp_api/apps/performance/tests/test_forms.py
mtp_api/apps/performance/updaters.py
mtp_api/apps/performance/view_dashboard.py

…because GDS have killed it off. The functionality for posting stats remains, but is no longer scheduled to run periodically.

Stop posting stats to GOV.UK Performance Platform

---

.gitignore
mtp_api/assets-src/javascripts/credit-report.js
mtp_api/assets-src/javascripts/dashboard.js
mtp_api/assets-src/javascripts/google-charts.js
mtp_api/assets-src/javascripts/performance-dashboard.js
mtp_api/assets-src/javascripts/performance-overview.js
mtp_api/assets-src/javascripts/satisfaction-results.js
mtp_api/assets-src/stylesheets/app-ie8.scss
mtp_api/assets-src/stylesheets/app.scss
mtp_api/assets-src/stylesheets/performance-dashboard.scss
mtp_api/templates/.gitignore
requirements/base.txt
requirements/dev.txt

The most important part of this PR is upgrading to mtp-common 11.3: 11.x before this one assumed that apps use a single-tree structure for building assets (scripts and stylesheets) whereas `api` actually keeps them in separate folders and does not make bundles.
In future, we want to have the api make asset bundles in the same fashion as other apps so it is not treated a special case.

Fix asset building and include latest dependencies from mtp-common

---

mtp_api/apps/mtp_auth/serializers.py
mtp_api/apps/mtp_auth/tests/test_views.py

In the context of intelligence tool, FIU users are equivalent to user admins.
If a security user is in `FIU` group they would also be in `UserAdmin`
group and vice versa.
The helper method `_make_user_admin()` was called just after the user's
groups were clear which meant the user was not added to `FIU` group as
intended.
See comment with more links to code: https://github.com/ministryofjustice/money-to-prisoners-api/pull/647#discussion_r615735071

Make 'security' user a UserAdmin makes them FIU

---

mtp_api/apps/mtp_auth/management/commands/send_account_request_emails.py
mtp_api/apps/mtp_auth/tests/test_account_request_emails.py

'security' account requests are not prison-specific.
These 'security' account requests are emailed to all the 'security' `UserAdmins`
(FIU), regardless of which prisons are associated to these `UserAdmins`.
The test for this command have been improved to separate the test for the
`find_admins()` method from the test which checks correct admins are emailed.
**NOTE**: The `mtp_auth/new_account_requests.(html|txt)` templates don't seem
to use the `prison_name` in the context so I've removed it.

'send_account_request_emails' works with requests without prison

---

mtp_api/apps/core/management/commands/delete_zendesk_tickets.py
mtp_api/apps/core/management/commands/run_scheduled_commands.py
mtp_api/apps/core/models.py
mtp_api/apps/core/templatetags/tick_charts.py
mtp_api/apps/core/views.py
mtp_api/apps/credit/management/commands/create_prisoner_credit_notices.py
mtp_api/apps/credit/models.py
mtp_api/apps/credit/tests/test_views/test_credit_list/__init__.py
mtp_api/apps/mtp_auth/management/commands/send_account_request_emails.py
mtp_api/apps/mtp_auth/validators.py
mtp_api/apps/notification/management/commands/send_notification_report.py
mtp_api/apps/performance/prediction.py
mtp_api/apps/performance/updaters.py
mtp_api/apps/prison/forms.py
mtp_api/apps/prison/serializers.py
mtp_api/apps/prison/utils.py
mtp_api/apps/security/managers.py
mtp_api/apps/security/views_admin.py
mtp_api/apps/transaction/views.py
requirements/base.txt
requirements/dev.txt

Jira: https://dsdmoj.atlassian.net/browse/MTP-1863
* Moved dynamic fields out of logger.error/warning and exceptions to allow for sentry to deduplicate
Note that i've left any exceptions propagate to the UI/API and do not touch Sentry alone (`ValidationError`, `InvalidStateForUpdateException` etc)
Depends on [common#419](https://github.com/ministryofjustice/money-to-prisoners-common/pull/419)

MTP-1863 Remove remaining identifiers from exceptions and attach to sentry metadata

---

mtp_api/apps/core/tests/utils.py
mtp_api/apps/credit/tests/test_private_estate.py
mtp_api/apps/notification/tests/test_commands.py
mtp_api/apps/prison/tests/utils.py
mtp_api/apps/security/tests/test_checks.py
mtp_api/apps/security/tests/test_views/test_check_views.py

Some of the `api` tests have been flaky, they'd sometimes randomly fail even when nothing related to that test changed or was broken.
Investigation these is not easy but we're thinking this is caused by the random nature of the test data. E.g. a number of payments or prisoner locations would be generated and sometimes this random data would cause some tests to fail.
Changes:
1. [updated `load_random_prisoner_locations()` test utility function](https://github.com/ministryofjustice/money-to-prisoners-api/commit/40ed6a3f3a6dd2c0732042703180528c60ec91fc) to always generate a batch of `PrisonerLocation` with **distinct prisoner numbers** (this is not enforced at model/DB level because when new locations are added we may temporarily have duplications, this is by design) - this should prevent …

MTP-1370: Flaky tests improvements

---

mtp_api/apps/credit/tests/test_private_estate.py

This test was sometimes failing because of some of the credits in the
private estate batch had a `received_at` from a different day:
https://app.circleci.com/pipelines/github/ministryofjustice/money-to-prisoners-api/940/workflows/92b6483e-a11c-4a4c-b7b5-0c914670bbd6/jobs/1952
Problem
-------
This was failing when one of the credits had a `received_at` close
to midnight, e.g. 00:30 BST (+01:00).
In the `setUp()` a UTC datetime was used to create the batches, this would
select credits between 00:00 UTC to 23:59 UTC causing the credit above to
mistakenly end into the batch for the previous day (because its
`received_at` was 23:30 UTC)
[The assertion](https://app.circleci.com/pipelines/github/ministryofjustice/money-to-prisoners-api/940/workflows/92b6483e-a11c-4a4c-b7b5-0c914670bbd6/jobs/1952) …

Fix flaky PrivateEstateBatch test

---

requirements/base.txt
requirements/dev.txt

As part of the migration to a newer version of Ubuntu (`20.04`) which
comes with Python 3.8.
Related to ticket: https://dsdmoj.atlassian.net/browse/MTP-1841

mtp-common 12.0.0: Only support Python 3.8+

---

mtp_api/apps/performance/forms.py
mtp_api/apps/performance/tests/test_views.py
mtp_api/apps/performance/views.py

Background
=========
Performance Data is derived from User Satisfaction data and from Digital Take-up data (among other things).
These weekly records are created/updated every Monday for the week of 2 weeks ago, to allow for late data (these are updated via [`update_performance_data`](https://github.com/ministryofjustice/money-to-prisoners-api/blob/b439932e864d2d29e186736ec7345ba72e2dc928/mtp_api/apps/performance/management/commands/update_performance_data.py) management command).
This changeset generate/update the Performance Data for the relevant week(s) when User Satisfaction/Digital Take-up is uploaded.
User Satisfaction
============
We tend to upload this CSV file on a monthly basis for the month before. 
On upload the completed weeks are updated, e.g. if last date in CSV file is a …

Update Performance data on User Satisfaction/Digital Take-up upload

---

mtp_api/apps/mtp_auth/patches.py
mtp_api/apps/mtp_auth/tests/test_patches.py

Invalid grant errors do not always have a description. An error with 'Invalid credentials given.' description should still be converted to 401 and others can still remain 400.

Fix oauth-provider patch

---

mtp_api/apps/core/management/commands/upload_dump_for_ap.py
mtp_api/apps/core/tests/test_upload_dump_for_ap.py

… because new kubernetes cluster using IRSA will not require assuming an IAM role. The code to assume the role will remain until application is fully migrated.

Relax prerequisite environment variable validation for uploading to Analytical Platform

---

.circleci/custom_scripts/deploy_test.sh

… rather than deriving from cluster name (which no longer works in new EKS cluster).

Configure k8s api server url for CircleCI directly

---

mtp_api/apps/credit/management/commands/fix_stuck_credits.py
mtp_api/apps/credit/tests/test_stuck_credits.py

When the cashbook posts transactions to NOMIS, it occasionally fails to update a batch as credited in the MTP api.
This means that credits correctly reach NOMIS (and the prisoner) but the MTP api is in an inconsistent state and the cashbook continues to display them as pending new credits.
The NOMIS api (theoretically) will not allow double-posting a transaction if someone retries to credit these in the cashbook.
This command matches old credits in the MTP DB that are thought to still be pending with transactions in NOMIS: if there is a one-to-one mapping and the NOMIS transaction IDs hadn't been used before, this command offers to link them and fix the problem.

Add management command to mark "stuck" credits as credited

---

api.ini
mtp_api/settings/base.py
mtp_api/tasks.py
requirements/base.txt
requirements/dev.txt

uWSGI now runs in lazy mode such that each process loads its own complete application rather than forking the master. This now requires the spooler to setup django.
Lazy apps are needed if telemetry is to be sent to Azure Application Insights: the `opencensus` library starts a background thread on launch to transport telemetry to Azure, but if uWSGI loads the application and _then_ forks, this thread is no longer accessible from the new process.
In `prod` environment:
• `mtp` logs of level INFO and higher
• other logs of level WARNING and higher
• 10% of requests traces
…will be sent.
Depends on [common#539](https://github.com/ministryofjustice/money-to-prisoners-common/pull/539).

MTP-1921: Improve Azure Application Insights request tracing and logging

---

mtp_api/apps/credit/tests/test_private_estate.py
mtp_api/apps/credit/tests/test_stuck_credits.py
mtp_api/apps/disbursement/tests/utils.py
mtp_api/apps/mtp_auth/tests/mommy_recipes.py
mtp_api/apps/mtp_auth/tests/test_account_request_emails.py
mtp_api/apps/mtp_auth/tests/test_login_counts.py
mtp_api/apps/mtp_auth/tests/test_views.py
mtp_api/apps/notification/tests/test_commands.py
mtp_api/apps/notification/tests/test_views.py
mtp_api/apps/notification/tests/utils.py
mtp_api/apps/performance/tests/test_update_performance_data.py
mtp_api/apps/performance/tests/test_views.py
mtp_api/apps/prison/tests/test_prisoner_balances.py
mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/security/management/commands/bulk_unmonitor.py
mtp_api/apps/security/management/commands/update_security_profiles.py
mtp_api/apps/security/tests/test_checks.py
mtp_api/apps/security/tests/test_commands.py
mtp_api/apps/security/tests/test_views/test_check_views.py
mtp_api/apps/user_event_log/tests/test_utils.py
requirements/base.txt

This is useful for when an FIU staff member leaves the group

Add management command to remove all monitors and saved searches for a given user

---

requirements/base.txt

…because there is no ARM build for this old version

Use source package for psycopg2 on macOS instead of pre-built binary

---

requirements/base.txt
requirements/dev.txt

MTP `api` shouldn't be sending any data to GA and its forms don't use the `django-form-error-reporting`'s mixins but it still makes sense to use the same version of `mtp-common` like the rest of the apps.

MTP-1937: Use latest version of `mtp-common`

---

mtp_api/apps/prison/tests/test_views.py
mtp_api/apps/prison/views.py

For 1 day, HMP Altcourse will not be accepting money. The precise timing is chosen based on [Worldpay cutoffs, i.e. midnight UTC](https://github.com/ministryofjustice/money-to-prisoners-bank-admin/blob/a4dd722fc5d0b83b25ddda683798d8e331391a45/mtp_bank_admin/apps/bank_admin/utils.py#L32C5-L40) with an hour either side just in case.

MTP-1956: Prevent Altcourse from receiving money on 30 May

---

mtp_api/apps/security/migrations/0036_monitoredpartialemailaddress.py
mtp_api/apps/security/models.py
mtp_api/apps/security/serializers.py
mtp_api/apps/security/tests/test_views/test_monitored_partial_email_address_views.py

#769 used an inappropriate base serialiser class which did not validate the `keyword` field properly. Now, failing keyword uniqueness and length checks will return a 400 instead of 500

MTP-1976: Ensure that monitored partial email address serialiser’s field validators run

---

.circleci/config.yml

Postgres 16.1 is deprecated and will be supported only until March 2024. 14.10 also include mitigations for several CVEs including CVE-2023-5869: https://www.postgresql.org/support/security/CVE-2023-5869/
See AWS Posgres release calendar:
https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-release-calendar.html
NOTE: This doesn't upgrade any database, it will just run the tests on a PosgreSQL 16.1 in CI.

MTP-1980: Postgres upgrade to version 16.1

---

mtp_api/apps/mtp_auth/management/commands/disable_inactive_users.py
mtp_api/apps/mtp_auth/tests/test_disable_inactive_users.py
requirements/base.txt

Users who have not logged in for 3 months count are set as inactive by a new management command.
Applies only to non-staff (i.e. those that cannot log into Django admin) and non-superadmin users of these mtp apps: cashbook, bank-admin & noms-ops

MTP-1931: Disable users who’ve not logged in for some time

---

mtp_api/apps/core/views.py
mtp_api/apps/credit/tests/test_base.py
mtp_api/apps/credit/tests/test_views/test_credit_list/test_credit_list_with_recieved_at_filter.py
mtp_api/apps/mtp_auth/admin.py
mtp_api/apps/mtp_auth/views.py
mtp_api/apps/performance/views.py
requirements/base.txt
requirements/dev.txt

- use newest version of mtp-common which bumps Django to version 5.2
- removed yet another use of `django.utils.timezone.utc`
- removed deprecated method `LogEntryManager.log_action()` method usage (https://github.com/ministryofjustice/money-to-prisoners-api/pull/825/commits/ea0f0e7f9d43c11a946a4f290eabf33b28bd1de8)
Here an example of some of the `LogEntry` records created locally while playing with the Django admin interface:

Django 5.2
