- .editorconfig
- Makefile
- README.md
This makes it a lot easier to run the server everyday.
> Provide Makefile for convenience

- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/views.py
- mtp_api/urls.py
This adds a `/users/<my-username>/` endpoint returning my user data.
Access to other's user data is not allowed.
This can be used to get user pk / full name and the prisons
that the user can manages.
> users endpoint returning my user data

- docker-compose.yml
Fixes an issue with a newer version of docker-compose: https://github.com/docker/compose/issues/1193
> Keep container running on `docker-compose up`

- mtp_api/apps/prison/migrations/0004_auto_20150811_1458.py
- mtp_api/apps/prison/models.py
This adds a multi column index on <prisoner_number> and <prisoner_dob> to speed up table joins.
> Add prisoner number/dob index on PrisonerLocation

- mtp_api/apps/core/tests/utils.py
- mtp_api/apps/mtp_auth/fixtures/initial_groups.json
- mtp_api/apps/mtp_auth/tests/mommy_recipes.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/urls.py
- mtp_api/apps/prison/tests/test_views.py
- mtp_api/apps/prison/urls.py
- mtp_api/apps/transaction/migrations/0008_auto_20150813_1314.py
- mtp_api/apps/transaction/models.py
- mtp_api/apps/transaction/serializers.py
- mtp_api/apps/transaction/signals.py
- mtp_api/apps/transaction/tests/test_views.py
- mtp_api/apps/transaction/tests/utils.py
- mtp_api/apps/transaction/urls.py
- mtp_api/apps/transaction/views.py
- mtp_api/urls.py
This adds a new bank-admin namespaced transactions endpoint with the ability
of creating transactions if you have the right permissions.
This also adds a new BankAdmin group with just POST permissions on
bank-admin/transactions/.
> Create transactions endpoint

- mtp_api/apps/core/management/commands/load_test_data.py
- mtp_api/apps/transaction/api/bank_admin/serializers.py
- mtp_api/apps/transaction/migrations/0012_remove_transaction_upload_counter.py
- mtp_api/apps/transaction/models.py
- mtp_api/apps/transaction/tests/test_bank_admin_views.py
- mtp_api/apps/transaction/tests/test_base.py
- mtp_api/apps/transaction/tests/test_cashbook_views.py
- mtp_api/apps/transaction/tests/utils.py
This is because it's not needed so it's better to remove it and simplify things.
> Remove Transaction.upload_counter

- docker-compose.yml
- docker_entrypoint.sh
Added a conditional to the docker_entrypoint.sh such that if the DOCKER_STATE env variable is set to 'reset_db' then on deployment to an environment the relevant DB will be wiped and the test data loaded.
> Reset test data

- Makefile
- README.md
- update the Makefile to use it
- update the instructions, and add details
> Make the Makefile use docker-machine, and improve instructions

- mtp_api/apps/mtp_auth/tests/mommy_recipes.py
- mtp_api/apps/transaction/api/cashbook/serializers.py
- mtp_api/apps/transaction/api/cashbook/views.py
- mtp_api/apps/transaction/models.py
- mtp_api/apps/transaction/tests/test_cashbook_views.py
adds additional filters to transactions/payments API and allows it to respond with more details on the transactions
[Partial #104090936]
> Transaction history

- .gitignore
- Dockerfile
- mtp_api/settings/base.py
needed to run Django admin properly
> makes the Docker build collect static files

- mtp_api/settings/base.py
- mtp_api/settings/prod.py
> tightens security for cookies and provides another layer to enforce SSL

- conf/uwsgi/magiclantern.ini
- mtp_api/apps/core/management/commands/clean_up.py
- mtp_api/apps/mtp_auth/management/commands/clear_oauth2_tokens.py
- mtp_api/settings/base.py
At 3am daily, clears out expired Django sessions and OAuth2 access/refresh tokens
> Run clean-up tasks periodically using uWSGI cron facility

- mtp_api/apps/account/migrations/0005_auto_20151118_1440.py
- mtp_api/apps/account/models.py
- mtp_api/apps/account/serializers.py
- mtp_api/apps/account/tests/test_views.py
This is to allow auditing, to see which user downloaded
which files.
> Record the user that created a batch

- mtp_api/apps/account/admin.py
- mtp_api/apps/account/migrations/0006_auto_20151119_1719.py
- mtp_api/apps/account/models.py
- mtp_api/apps/account/serializers.py
- mtp_api/apps/account/tests/test_views.py
- mtp_api/apps/transaction/api/bank_admin/views.py
- mtp_api/apps/transaction/tests/test_bank_admin_views.py
Also removing the balance model as we cannot reliably track the balance.
> Delimit transactions by date

- mtp_api/apps/core/forms.py
- mtp_api/apps/core/management/commands/delete_all_data.py
- mtp_api/apps/core/management/commands/load_test_data.py
- mtp_api/apps/core/views.py
useful for prisoner location and bank admin testing
> Create an admin interface and management command to clear the DB

- mtp_api/apps/transaction/api/bank_admin/serializers.py
- mtp_api/apps/transaction/constants.py
- mtp_api/apps/transaction/managers.py
- mtp_api/apps/transaction/migrations/0018_transaction_category.py
- mtp_api/apps/transaction/migrations/0019_transaction_ref_code.py
- mtp_api/apps/transaction/models.py
- mtp_api/apps/transaction/tests/test_bank_admin_views.py
- mtp_api/apps/transaction/tests/utils.py
- mtp_api/settings/base.py
Handle the upload of debit transactions, which do not need to be processed
by prison staff but which are returned in the bank statement.
Also deal with generating a daily unique ref code for credits.
> Handle debits

- mtp_api/apps/account/admin.py
- mtp_api/apps/account/migrations/0007_balance.py
- mtp_api/apps/account/models.py
- mtp_api/apps/account/serializers.py
- mtp_api/apps/account/tests/test_views.py
- mtp_api/apps/account/urls.py
- mtp_api/apps/account/views.py
- mtp_api/apps/mtp_auth/fixtures/initial_groups.json
This is to facilitate the display of the current balance
in the bank statements.
> Track balance

- mtp_api/apps/transaction/api/bank_admin/serializers.py
- mtp_api/apps/transaction/api/bank_admin/views.py
- mtp_api/apps/transaction/migrations/0020_auto_20151203_0955.py
- mtp_api/apps/transaction/models.py
- mtp_api/apps/transaction/tests/test_bank_admin_views.py
This is so that the transaction uploader can work out which files to process.
> Support checking last upload date

- docker_entrypoint.sh
This functionality has been replaced by admin management
commands.
> Remove 'reset_db' docker task

- mtp_api/apps/core/admin.py
- mtp_api/apps/core/forms.py
- mtp_api/apps/transaction/admin.py
- mtp_api/assets/admin/css/filter_form.css
- mtp_api/assets/admin/js/calendar_overrides.js
- mtp_api/settings/base.py
- mtp_api/templates/core/admin_form_filter.html
This adds filters to the admin view to allow an admin to view the outstanding credits per prison. This is for analytics purposes, and to help with this a date range filter was also added.
> Outstanding credits view

- mtp_api/apps/core/views.py
- mtp_api/apps/mtp_auth/validators.py
- mtp_api/apps/transaction/api/bank_admin/views.py
- mtp_api/apps/transaction/api/cashbook/views.py
- mtp_api/settings/base.py
… which are not already covered by client applications
> Add logging at key points in api transactions

- Makefile
- mtp_api/apps/core/tests/__init__.py
- mtp_api/settings/base.py
> Silence make tasks' python warnings if verbosity is set to zero

- mtp_api/apps/transaction/tests/test_cashbook_views.py
- mtp_api/apps/transaction/tests/utils.py
… only make dates timezone aware after all shifting is finished
> Fix tests around daylight savings switches

- mtp_api/apps/account/admin.py
- mtp_api/apps/account/models.py
- mtp_api/apps/prison/admin.py
- mtp_api/apps/transaction/admin.py
- mtp_api/apps/transaction/models.py
- mtp_api/apps/transaction/utils.py
- mtp_api/templates/admin/auth/user/change_form.html
the most useful of which are searching for prisoner locations by prisoner number and grouping transactions by received date
> Admin improvements

- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/settings/base.py
- mtp_api/templates/mtp_auth/new_user.txt
- requirements/base.txt
This includes full login credentials.
> Email a user newly created via the API with their account details

- mtp_api/apps/core/admin.py
- mtp_api/apps/prison/admin.py
This can be a useful feature for tracking down the intended
target of erroneous transactions.
> Allow for search of prisoner locations by DOB

- mtp_api/apps/core/dashboards.py
- mtp_api/apps/core/tests/utils.py
- mtp_api/apps/mtp_auth/constants.py
- mtp_api/apps/mtp_auth/fixtures/initial_groups.json
- mtp_api/apps/mtp_auth/permissions.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/tests/utils.py
- mtp_api/apps/prison/views.py
Modify client ID to reflect ploc -> nops change and add 'Security' auth group.
> Add security group

- README.md
- mtp_api/apps/credit/models.py
- mtp_api/apps/credit/serializers.py
- mtp_api/apps/credit/tests/test_views.py
Also change 'sender' to 'sender_name' for consistency.
> Add payment info to credit api

- mtp_api/settings/base.py
- requirements/dev.txt
- requirements/docker.txt
> Increase version requirement for mtp_common

- mtp_api/apps/transaction/dashboards.py
- mtp_api/templates/core/dashboard/transaction-report.html
as opposed to transactions, which are less interesting
> Link dashboard stats view to credits list

- mtp_api/apps/transaction/dashboards.py
This avoids copying the reference validation regex.
> Use presence of prisoner info fields to identify well formed reference

- mtp_api/apps/credit/tests/test_views.py
- mtp_api/apps/credit/views.py
This allows a user to include invalid credits in responses from the
credit API, upon provision of the 'include_invalid' parameter.
Also fixes a bug where the subset of the last element of a grouped
response was not being ordered.
> Allow retrieval of invalid credits and fix subgroup ordering

- mtp_api/apps/transaction/dashboards.py
Slightly more interesting than displaying nothing.
In order to accomplish this the TransactionReportChart class becomes
responsible for generating its own date-ranged queryset.
> Display a one week chart on the 'transactions today' dashboard

- mtp_api/apps/transaction/constants.py
- mtp_api/apps/transaction/dashboards.py
- mtp_api/apps/transaction/models.py
- mtp_api/apps/transaction/utils.py
- mtp_api/assets/core/css/transaction-report.css
- mtp_api/templates/core/dashboard/module.html
- mtp_api/templates/core/dashboard/transaction-report.html
> Add more useful transactions to dashboard

- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/tests/test_views.py
this is necessary for login views to restrict users who do not have access to the specific app
> User api reports the applications a user has access to

- mtp_api/apps/mtp_auth/admin.py
- mtp_api/apps/transaction/tests/test_views.py
Fix test to verify that anonymous payments do not receive a ref code.
> Fix reconciliation test for anonymous payments

- mtp_api/apps/core/filters.py
- mtp_api/apps/credit/tests/test_views.py
- mtp_api/apps/credit/views.py
- requirements/dev.txt
- requirements/docker.txt
…because django-filters ignores '' in character filters
> Add filters to credits api for selecting sender fields that are blank strings

- mtp_api/apps/core/management/commands/load_test_data.py
- mtp_api/apps/prison/fixtures/test_nomis_mtp_prisons.json
Also includes region, categories and population types for these
prisons.
> Add a fixture containing all of the prisons that will use MTP

- mtp_api/apps/core/admin.py
- mtp_api/apps/core/management/commands/run_scheduled_commands.py
Add transaction to ensure atomicity of job timing updates.
> Fix scheduled jobs not appearing in admin

- mtp_api/apps/credit/forms.py
- mtp_api/apps/credit/serializers.py
- mtp_api/apps/credit/views.py
mainly by removing inner queries and adding indexing to intermediate tables
> Security search optimisation

- mtp_api/apps/performance/management/commands/update_performance_platform.py
- mtp_api/apps/performance/tests/test_updaters.py
- mtp_api/apps/performance/updaters.py
- mtp_api/settings/base.py
- requirements/base.txt
Allows for the creation of updaters, which function to update a particular
resource on the govuk performance platform.
> Add command to update performance platform data

- mtp_api/apps/credit/tests/test_views.py
…because [postgres collates ignoring spaces](https://wiki.postgresql.org/wiki/FAQ#Why_do_my_strings_sort_incorrectly.3F)
> Produce reliable set of credits for testing ordering by prisoner name

- mtp_api/apps/core/management/commands/delete_zendesk_tickets.py
(That were last updated over two weeks ago)
> Delete solved as well as closed zendesk tickets

- mtp_api/apps/credit/__init__.py
- mtp_api/apps/credit/managers.py
- mtp_api/apps/credit/models.py
- mtp_api/apps/credit/tests/test_views.py
- mtp_api/apps/credit/views.py
- Moved business logic from the views to the manager class.
- Batched all update/create operations
- Use select_for_update to ensure concurrency safety
> Refactor credit processing operations

- mtp_api/apps/credit/managers.py
- mtp_api/apps/transaction/serializers.py
- mtp_api/apps/transaction/views.py
Additionally batch log creation.
> Move refunding business logic from view to manager

- mtp_api/apps/credit/views.py
This is to make it possible for a user to both use the cashbook
with the correctly limited set and use the security tool with
all credits available, or to use the security tool limited by
prison.
> Improve credit filtering by access level and client

- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/views.py
and include deactivated users in user list
> Report whether a user is active in API

- mtp_api/apps/core/management/commands/run_scheduled_commands.py
In order to avoid a long running command from blocking other attempts
to run the scheduled commands job:
a) Only lock one row (the current command) at a time, rather than locking
the entire table for writing.
b) If a row cannot be locked for writing, raise an exception and then
continue execution rather than blocking.
> Lock one row at a time and do not block when running scheduled commands

- mtp_api/templates/admin/auth/user/change_form.html
- mtp_api/translations/cy/LC_MESSAGES/django.po
- mtp_api/translations/en_GB/LC_MESSAGES/django.po
and make adding apps and prisons to user a little easier
> Show user’s registered prison on user editing page

- mtp_api/apps/mtp_auth/admin.py
- mtp_api/apps/payment/admin.py
Allows for searching user mappings by username, and payments
by last 4 digits of card number.
> Add useful search fields to django admin

- mtp_api/apps/performance/tests/test_updaters.py
- mtp_api/apps/performance/updaters.py
- mtp_api/settings/base.py
Daily update of number of transactions via digital and post
(where available).
> Add performance platform updater for digital takeup

- .dockerignore
- .gitignore
- Dockerfile
- api.ini
- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/views.py
- mtp_api/tasks.py
- requirements/dev.txt
- requirements/docker.txt
and make uwsgi.ini usable outside docker
> Use MTP-common’s spoolable mechanism for email sending

- Dockerfile
- api.ini
- requirements/dev.txt
- requirements/docker.txt
This updates
• the base container to Ubuntu Xenial
• node.js to version 8
• python to version 3.5
> Docker upgrades

- mtp_api/apps/core/admin.py
- mtp_api/apps/core/dashboards.py
- mtp_api/apps/core/views.py
- mtp_api/apps/credit/dashboards.py
- mtp_api/apps/credit/tests/test_dashboard.py
- mtp_api/assets-src/javascripts/credit-report.js
- mtp_api/assets-src/javascripts/dashboard.js
- mtp_api/assets-src/stylesheets/credit-report.scss
- mtp_api/assets-src/stylesheets/dashboard.scss
- mtp_api/templates/core/dashboard/credit-report-cells/creditable.html
- mtp_api/templates/core/dashboard/credit-report.html
- mtp_api/templates/core/dashboard/index.html
- mtp_api/templates/core/dashboard/module.html
but it's still too slow to work on `prod`
> Fix broken dashboard

- mtp_api/apps/account/tests/test_views.py
- mtp_api/apps/core/tests/utils.py
- mtp_api/apps/credit/tests/test_base.py
- mtp_api/apps/disbursement/tests/test_views.py
- mtp_api/apps/mtp_auth/fixtures/initial_groups.json
- mtp_api/apps/mtp_auth/tests/mommy_recipes.py
- mtp_api/apps/mtp_auth/tests/test_permissions.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/tests/utils.py
- mtp_api/apps/payment/tests/test_views.py
- mtp_api/apps/prison/tests/test_views.py
- mtp_api/apps/security/tests/test_commands.py
- mtp_api/apps/security/tests/test_models.py
- mtp_api/apps/security/tests/test_views.py
- mtp_api/apps/service/tests/test_notifications.py
- mtp_api/apps/transaction/tests/test_base.py
Additionally refactor test user generation slightly.
> Add a separate group for disbursement bank admin permissions

- mtp_api/apps/disbursement/serializers.py
which gets prefixed with "PMD" starting from id 100 for easier searching in AP
> Add invoice number to disbursements

- mtp_api/apps/credit/serializers.py
- mtp_api/apps/disbursement/serializers.py
Otherwise you can end up with a null pointer further down the line.
> Return created instance from create method of comment serializers

- mtp_api/apps/performance/views.py
- mtp_api/templates/admin/performance/prison_performance.html
Which for the most part totally weren't there until Igor made me
change stuff.
> Fix errors with prison performance page

- mtp_api/apps/performance/prediction.py
- mtp_api/apps/performance/tests/test_prediction.py
and there was a mistake in `curve_point_to_date`
> Use better curve parameters for digital take-up report

- mtp_api/apps/core/main.py
- mtp_api/apps/credit/templatetags/credit.py
- mtp_api/apps/performance/view_dashboard.py
- mtp_api/assets-src/javascripts/performance-dashboard.js
- mtp_api/assets-src/stylesheets/performance-dashboard.scss
- mtp_api/templates/performance/dashboard.html
> Dashboard tweak

- mtp_api/apps/credit/notices/prisoner_credits.py
- mtp_api/apps/credit/tests/test_notices.py
- requirements/dev.txt
- requirements/docker.txt
rather than forcing Wing, Landing, Cell as there are variations
> Use provided prisoner location level types

- mtp_api/apps/core/tests/utils.py
- mtp_api/apps/mtp_auth/admin.py
- mtp_api/apps/mtp_auth/migrations/0010_accountrequest.py
- mtp_api/apps/mtp_auth/models.py
- mtp_api/apps/mtp_auth/permissions.py
- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/urls.py
- mtp_api/apps/mtp_auth/views.py
- mtp_api/apps/prison/views.py
- mtp_api/templates/mtp_auth/account_request_denied.html
- mtp_api/templates/mtp_auth/account_request_denied.txt
- mtp_api/templates/mtp_auth/user_moved.html
- mtp_api/templates/mtp_auth/user_moved.txt
to support:
* new users signing up
* existing users changing roles
* existing users changing prison set
> Account requests

- mtp_api/apps/core/models.py
- mtp_api/apps/core/permissions.py
- mtp_api/apps/core/tests/test_admin.py
- mtp_api/apps/core/tests/test_permissions.py
- mtp_api/apps/core/views.py
- mtp_api/apps/mtp_auth/admin.py
- mtp_api/apps/prison/models.py
- mtp_api/settings/base.py
- requirements/base.txt
Required upgrading oauth-toolkit library as well.
> Upgrade Django version to 2.0

- mtp_api/apps/disbursement/tests/test_views.py
The current functionality depends on the vagaries of the Django ORM
framework, and if this behaviour is ever changed then it may cause
significant issues.
> Add test to ensure that retrieving disbursement by logged time works

- mtp_api/apps/core/permissions.py
- mtp_api/apps/core/tests/test_permissions.py
- mtp_api/apps/core/tests/utils.py
- mtp_api/apps/mtp_auth/admin.py
- mtp_api/apps/mtp_auth/migrations/0012_flags.py
- mtp_api/apps/mtp_auth/models.py
- mtp_api/apps/mtp_auth/permissions.py
- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/tests/mommy_recipes.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/urls.py
- mtp_api/apps/mtp_auth/views.py
NB: this now allows non-admin users editing themselves and self-deactivating
> User flags

- README.md
- mtp_api/apps/core/admin.py
- mtp_api/apps/core/models.py
- mtp_api/apps/credit/managers.py
- mtp_api/apps/credit/tests/test_base.py
- mtp_api/apps/credit/tests/test_views.py
- mtp_api/apps/credit/views.py
- mtp_api/apps/mtp_auth/serializers.py
- mtp_api/apps/mtp_auth/tests/utils.py
- mtp_api/apps/mtp_auth/views.py
- mtp_api/apps/performance/dashboards.py
- mtp_api/apps/performance/models.py
- mtp_api/apps/performance/view_dashboard.py
- mtp_api/apps/security/tests/test_views.py
- mtp_api/apps/transaction/tests/test_base.py
- mtp_api/apps/transaction/tests/test_views.py
- mtp_api/apps/transaction/views.py
This:
- adds/corrects a few lines in the README
- removes unused lines
- makes sure mutable data structures are not used for arg defaults
- changes another couple of things
The intention is to eventually add `flake8-bugbear` and `flake8-quotes` to mtp_common.
> Housekeeping

- mtp_api/apps/disbursement/tests/test_views.py
- mtp_api/apps/disbursement/tests/utils.py
- mtp_api/apps/disbursement/views.py
This adds a new simple_search search param to the disbursement list view which makes an icontains lookup on multiple text fields.
> Add simple_search search param to disbursement list view

- mtp_api/apps/security/serializers.py
- mtp_api/apps/security/tests/test_views.py
- mtp_api/apps/security/views.py
This adds a new simple_search search param to the prisoner list view which makes an icontains lookup on multiple text fields.
It also adds a couple of extra fields to the response data.
> Add simple_search search param to prisoner list view

- mtp_api/apps/disbursement/models.py
- mtp_api/apps/notification/management/commands/send_notification_report.py
- mtp_api/apps/notification/rules.py
- mtp_api/apps/notification/tests/test_commands.py
- mtp_api/apps/prison/models.py
- mtp_api/apps/security/management/commands/update_security_profiles.py
- requirements/base.txt
only includes simple rules and monitoring rules apply when _somebody_ monitors, not a given user
> Notification report generation

- mtp_api/apps/core/management/commands/dump_for_ap.py
- mtp_api/apps/core/tests/test_dump_for_ap.py
- mtp_api/apps/credit/managers.py
- mtp_api/apps/credit/models.py
- mtp_api/apps/disbursement/managers.py
- mtp_api/apps/notification/management/commands/send_notification_report.py
for exporting records to analytical platform
> Add a simple CSV-dumping management command

- mtp_api/apps/core/admin.py
- mtp_api/apps/core/app.py
- mtp_api/apps/core/forms.py
- mtp_api/apps/core/management/commands/load_test_data.py
- mtp_api/apps/core/models.py
- mtp_api/apps/core/permissions.py
- mtp_api/apps/core/serializers.py
- mtp_api/apps/core/tests/test_tokens.py
- mtp_api/apps/core/tests/utils.py
- mtp_api/apps/core/urls.py
- mtp_api/apps/core/views.py
- mtp_api/apps/credit/tests/test_notices.py
- mtp_api/settings/base.py
- mtp_api/templates/core/nomis-token.html
- requirements/dev.txt
- requirements/docker.txt
This mainly refactor tests, removes some old unused code and adds settings to support the new NOMIS Elite2 API.
> NOMIS Elite2 API

- mtp_api/apps/payment/serializers.py
- mtp_api/apps/payment/tests/test_views.py
so that send-money can capture or cancel payments
> Serialise security check within payment responses

- mtp_api/apps/security/views.py
c.f. https://www.django-rest-framework.org/api-guide/filtering/?q=default_ordering#specifying-a-default-ordering
> Add ordering filter to checks view and fix default ordering settings

- mtp_api/apps/notification/management/commands/send_notification_report.py
- mtp_api/apps/notification/rules.py
- mtp_api/apps/security/managers.py
- mtp_api/apps/security/tests/test_checks.py
…such that more than 2 events need to happen in 1 week (previously more than 4 in 4 weeks)
> Tighten credit frequency rules

- mtp_api/apps/security/views.py
https://dsdmoj.atlassian.net/browse/MTP-1453 
The only change to this PR is to add the `assigned_to` filter on `CheckListFilter`
> MTP-1453 my list page

- requirements/base.txt
- requirements/dev.txt
- requirements/docker.txt
…and update uwsgi and django-anymail dependencies that include bug fixes [MTP-1519](https://dsdmoj.atlassian.net/browse/MTP-1519) (depends on [common-380](https://github.com/ministryofjustice/money-to-prisoners-common/pull/380))
> Use a single consistent version requirement for Django in all apps

- mtp_api/settings/base.py
These are necessary for running in docker locally to mtp_api/settings/base.py
> Explicitly commited the dev ALLOWED_HOSTS settings 

- mtp_api/apps/prison/admin.py
…in django admin so that it's easier to tell when any prison is behind on their reports
> Show when each prison's account balances were last updated

- mtp_api/apps/core/management/commands/dump_for_ap.py
…from when billing address was not recorded
> Fix exporting of very old debit card credits for Analytical Platform

- mtp_api/apps/prison/admin.py
Name is not available, this should have searched by number
> Fix searching for prisoner balances in django admin

- requirements/base.txt
https://github.com/ministryofjustice/money-to-prisoners-api/security/dependabot/requirements/base.txt/djangorestframework/open
> Updated djangorestframework due to XSS vulnerability, automatically update w/ patch releases

- mtp_api/apps/mtp_auth/tests/test_login_counts.py
- mtp_api/apps/mtp_auth/views.py
This mysterious bug caused the disappearing of March in the Staff Login
report table header.
On Sunday 29 March 2020 the clocks went forward to get more daylight
(this is called Daylight Saving Time, or DST for short).
This started the period of the year called British Summer Time (BST) ending
the Greenwich Mean Time (GMT) period:
- 1 March 2020 GMT (UTC +00:00)
- 1 April 2020 BST (UTC +01:00)
Because of the way we were calculating the beginning of the current month
and the previous 3 ones, by using the current day (timezone aware)
and by replacing the month component, that datetime object retained the
same timezone info, including the offset from UTC time.
Unfortunately, 1st of March and 1st of February are not in BST but
are in GMT which means when converted to localtime using the wrong …
> MTP-1428: Fix missing month in Staff Logins report

- mtp_api/apps/security/tests/utils.py
- mtp_api/apps/security/views.py
Jira: https://dsdmoj.atlassian.net/browse/MTP-1735
Linked PR: https://github.com/ministryofjustice/money-to-prisoners-noms-ops/pull/513
> MTP-1735 auto accept review page

- mtp_api/apps/mtp_auth/permissions.py
- mtp_api/apps/mtp_auth/tests/test_views.py
- mtp_api/apps/mtp_auth/views.py
Jira: https://dsdmoj.atlassian.net/browse/MTP-1805
Linked PRs:
* Cashbook: ministryofjustice/money-to-prisoners-cashbook#542
* Common: https://github.com/ministryofjustice/money-to-prisoners-common/pull/412
> MTP-1805 Request an Account

- mtp_api/apps/core/dashboards.py
Some of the surveys and/or questions have gone now and this dashboard raises
an exception while trying to get this data:
https://sentry.io/organizations/ministryofjustice/issues/2139335407/?environment=prod&project=2098210
This is caused by the fact the HTTP response is probably a non-200
but we try to get the data out of the response body anyway.
I've added `requests`' `raise_for_status()` and handling the requests
exception by logging them and by not adding the question to the dashboard
results
> Handle SatisfactionDashboard failing requests

- .editorconfig
- mtp_api/urls.py
C.f. https://ministryofjustice.github.io/security-guidance/implement-security-txt/
> Add /.well-known/security.txt redirect

- mtp_api/settings/base.py
…at 20% sample rate in production (this is a very high traffic app) and 100% in other environments.
> Turn on Sentry.io performance monitoring

- mtp_api/settings/base.py
- mtp_api/settings/docker.py
- requirements/base.txt
- requirements/dev.txt
and make settings configuration a bit simpler
> Fix Sentry SDK initialisation

- Dockerfile-dev
- docker-entrypoint.sh
- mtp_api/settings/base.py
…to make all MTP apps easier to run locally in concert
Depends on [mtp-common#429](https://github.com/ministryofjustice/money-to-prisoners-common/pull/429)
> Update docker-compose spec

- mtp_api/apps/core/dump.py
- mtp_api/apps/core/management/commands/dump_and_upload_for_ap.py
- mtp_api/apps/core/management/commands/dump_for_ap.py
- mtp_api/apps/core/management/commands/upload_dump_for_ap.py
- mtp_api/apps/core/tests/test_dump_and_upload_for_ap.py
- mtp_api/apps/core/tests/test_dump_for_ap.py
- mtp_api/apps/core/tests/test_upload_dump_for_ap.py
- mtp_api/apps/credit/dump.py
- mtp_api/apps/disbursement/dump.py
- mtp_api/apps/security/dump.py
This will allow the export of data to be more configurable and provide more information to the Analytical Platform.
Foundational step to implement export to Linkspace #666 / [MTP-1873](https://dsdmoj.atlassian.net/browse/MTP-1873)
Analytical Platform will now also get data about:
• credits that were rejected by FIU (and why)
• who is monitored currently by FIU
• relationships that are auto-accepted without manual FIU checks
> Improve data exporting tool

- requirements/base.txt
- requirements/dev.txt
…otherwise you cannot reset data in `test` environment
> Move dependencies required for random data creation to always be available

- mtp_api/apps/mtp_auth/migrations/0018_Add_UserAdmin_group_to_FIU.py
- mtp_api/apps/mtp_auth/migrations/0020_flag_cashbook_uas_to_confirm_credit_notice_email.py
- mtp_api/apps/mtp_auth/permissions.py
- mtp_api/apps/mtp_auth/tests/test_permissions.py
- mtp_api/apps/prison/models.py
- mtp_api/apps/prison/serializers.py
- mtp_api/apps/prison/tests/test_views.py
- mtp_api/apps/prison/urls.py
- mtp_api/apps/prison/views.py
… in order to service a new settings page that will be added to cashbook allowing admins to change these emails
> Allow cashbook user admins to list and edit prisoner credit notice emails

- .circleci/custom_scripts/deploy_test.sh
- .circleci/custom_scripts/ecr_cleanup.sh
- .circleci/custom_scripts/push_docker_image.sh
- .github/actions/clean-ecr/entrypoint.py
- .github/workflows/clean-ecr.yml
Depends on [mtp-deploy#352](https://github.com/ministryofjustice/money-to-prisoners-deploy/pull/352)
> Update app build, deploy and cleanup pipelines to use `main` as the default branch name

- mtp_api/apps/prison/tests/test_views.py
- mtp_api/apps/prison/views.py
… by considering whether there are any "recent" inactive locations.
Inactive locations are created as batches of the report are uploaded and there will be none left after completion.
An upload takes ~3min so older inactive locations are probably from a failed older upload and can be ignored; allowing a new upload to be started.
> Add api action to check whether a prisoner location report can be uploaded now

- mtp_api/apps/credit/management/commands/send_prisoner_credit_notices.py
- mtp_api/apps/notification/management/commands/send_notification_report.py
… otherwise scheduled jobs error-out and get stuck in a loop. Error logs are reported in Sentry in the same way as uncaught attachment-is-too-large exceptions, but prevent infinite loops.
> Log an error if an attachment is too large to send with GOV.UK Notify

- mtp_api/settings/base.py
https://dsdmoj.atlassian.net/browse/MTP-1921
> MTP-1921: configure requests being sent to AppInsights

- mtp_api/apps/mtp_auth/views.py
- mtp_api/apps/security/views.py
…which is used by user management views from mtp-common and included in mtp-cashbook, mtp-bank-admin and mtp-noms-ops
> Allow filtering and sorting of users list endpoint

- mtp_api/assets-src/stylesheets/performance-dashboard.scss
- requirements/base.txt
- requirements/dev.txt
- run.py
Nothing significant, just minor library version bumps
> MTP-1980: Update dependencies

- mtp_api/apps/credit/notices/__init__.py
- mtp_api/translations/cy/LC_MESSAGES/django.po
- mtp_api/translations/en_GB/LC_MESSAGES/django.po
- requirements/base.txt
- requirements/dev.txt
Depends on [mtp-common#635](https://github.com/ministryofjustice/money-to-prisoners-common/pull/635)
> MTP-1943: Rename HMPPS to reflect the accession of His Majesty King Charles III

- mtp_api/apps/core/management/commands/dump_for_linkspace.py
- mtp_api/apps/credit/dump.py
…and into Analytical Platform as a side effect
> MTP-2030: Export FIU security check decision reason into Linkspace
